### ISSUE TITLE
Add service types

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-discovery/ga4gh-service-info#2]
The current payload specifies a `name` field. We should consider if this needs to be handled partly with a controlled vocab field (enum) but defined externally. May allow flexibility of other services to provide a name but also allow us to know what type of service we're talking to

**Comment by mcupak** [comment]
I think we should have this in a `type` field. As for the format, the options are effectively:

1.  URI (e.g. `https://github.com/ga4gh-beacon/specification`)
2. URN (e.g. `urn:ga4gh:beacon`)
3. string (e.g. `BEACON`)

Personally, I like 2, because it provides implicit namespacing. 1 suggests there might be something machine-resolvable on the URL, which might not be the case. 3. requires we standardize the vocabulary somewhere.

**Comment by mcupak** [comment]
Jordi +1 for enumeration
Andy +1 for URN with enumeration

**Comment by mcupak** [comment]
Also version needed (Andy + Miro +1).

**Comment by andrewyatz** [comment]
Autism will want to use non-GA4GH services so the feeling is more towards URN and version. There is a corresponding issue in service registry, which mirrors this discussion. Miro to provide context

**Comment by andrewyatz** [comment]
This can be closed
